spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://localhost:5432/gamified_tracker
        username: lydazacklin
        password: 0680
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    server:
        port: 8080

    encryption:
        aes:
            key: "your-super-secret-32-byte-key!!"