spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://localhost:5432/gamified_tracker
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: ${GITHUB_CLIENT_ID}
                        clientSecret: ${GITHUB_CLIENT_SECRET}
server:
        port: 8080

encryption:
        aes:
          key: ${ENCRYPTION_AES_KEY}